### ISSUE TITLE
Switch to another spinner

### ISSUE THREAD

**Issue by redaxmedia** [redaxmedia/handpick#17]
Give the mico-spinner or nanospinner a try as speed via npx matters:

https://github.com/enemycnt/mico-spinner
https://github.com/usmanyunusov/nanospinner

**Comment by redaxmedia** [comment]
Done

**Comment by usmanyunusov** [comment]
Are you waiting for the stable version nanospinner?

**Comment by redaxmedia** [comment]
@usmanyunusov To be honest: not sure if I continue to use a third party spinner in the future or write my private one in TypeScript.

**Comment by usmanyunusov** [comment]
Better yours
