### ISSUE TITLE
Idea: handpick update command

### ISSUE THREAD

**Issue by GregOnNet** [redaxmedia/handpick#19]
Hi,

thanks for providing handpick. 🙏 

Recently I updated all packages of a customer's project.
I forgot about updating the version numbers of handpick's package-declarations.

It would be nice to have a command like `handpick update` that automatically updates all version numbers according to the packages defined in `dependencies/devDependencies`.

**Comment by redaxmedia** [comment]
Thanks for the great suggestion. You gonna love the tool named [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) that exactly does that. You either install it globally on your system try it first via npx.

![screenshot](https://user-images.githubusercontent.com/1835397/140434129-1a6d0487-9cc3-4f0b-bcfe-e44e3903f9d6.png)

Check for possible upgrades:
```
npx ncu
```

Automatically upgrade offical and custom dependencies:

```
npx ncu --upgrade
```

**Comment by redaxmedia** [comment]
I reopened the issue while realising the request was something similar. I keep this feature request open for the TypeScript rewrite.

**Comment by redaxmedia** [comment]
Solve via https://github.com/redaxmedia/handpick/commit/36930aad509fddd285baba90c88a969db626838b by introducing a reference feature for upcoming release 4.0.0-beta.1 ...

```json
{
	"name": "handpick",
	"version": "1.0.0",
	"dependencies":
	{
		"a": "1.0.0",
		"b": "1.0.0"
	},
	"devDependencies":
	{
		"c": "1.0.0",
		"d": "1.0.0",
		"e": "1.0.0",
		"f": "1.0.0"
	},
	"buildDependencies":
	{
		"a": "@dependencies",
		"b": "@dependencies"
	},
	"lintDependencies":
	{
		"c": "@devDependencies",
		"d": "@devDependencies"
	}
}
```

Is going to be resolvd to:

```json
{
	"name": "handpick",
	"version": "1.0.0",
	"__dependencies":
	{
		"a": "1.0.0",
		"b": "1.0.0"
	},
	"__devDependencies":
	{
		"c": "1.0.0",
		"d": "1.0.0",
		"e": "1.0.0",
		"f": "1.0.0"
	},
	"buildDependencies":
	{
		"a": "@dependencies",
		"b": "@dependencies"
	},
	"lintDependencies":
	{
		"c": "@devDependencies",
		"d": "@devDependencies"
	},
	"dependencies":
	{
		"a": "1.0.0",
		"b": "1.0.0",
		"c": "1.0.0",
		"d": "1.0.0"
	}
}

```
