### ISSUE TITLE
New version is causing a crash on our existing build

### ISSUE THREAD

**Issue by jlaule** [redaxmedia/handpick#23]
We have a Dockerfile building an image for testing and it is failing now that it is installing handpick@5.0.0.  Everything was working fine when it was using 3.2.1.

Here is the error that gets generated when we execute the handpick command
```
(node:8) UnhandledPromiseRejectionWarning: TypeError: this.stream.clearLine is not a function
    at SpinnerClass.stop (file:///usr/local/lib/node_modules/handpick/src/spinner.class.js:40:21)
    at SpinnerClass.error (file:///usr/local/lib/node_modules/handpick/src/spinner.class.js:36:41)
    at file:///usr/local/lib/node_modules/handpick/src/core.class.js:91:48
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It appears to be due to the new spinner section in the .handpick configuration file.  Apparently the new software does not handle it if the .handpick file is not updated to contain the information.  Not exactly sure what the spinner is supposed to be doing.  Can you add some documentation as to what is required for this and what it will provide as a result?

**Comment by redaxmedia** [comment]
I apologize to break your builds... so you are using node 8? what does it run on?

You can use `npx handpick@3`for the moment.

**Comment by jlaule** [comment]
I am not certain why that is showing node 8 because it is actually running on node 14.16 with npm 6.14.11

**Comment by redaxmedia** [comment]
This must be related to missing TTY support... https://stackoverflow.com/questions/34570452/node-js-stdout-clearline-and-cursorto-functions

First I have to reproduc the bug on my Ubuntu and later on properly us the readline module. I will release a fix asap.

**Comment by redaxmedia** [comment]
I skipped reproducing it and give it a quick shot by releasing "5.0.1-beta.1" as I cannot break more than already is broken.

Let me know if this works... keep in mind that npx takes a little bit to fetch the latest release

**Comment by redaxmedia** [comment]
I could now reproduce it with a freaking simple dockerfile:

```
# syntax=docker/dockerfile:1

FROM node
RUN npx handpick@5.0.1-beta.1
```

This works compared to 5.0.0 ...

**Comment by jlaule** [comment]
Cool, I was working on verifying with ours but glad you could verify quicker.

**Comment by jlaule** [comment]
Only bad thing is that with the new output, it generates a lot of info into CI/CD Pipeline processing using gitlab while it is executing the handpick.  Not a big deal but just thought I would let you know.  Thanks again for getting a quick turn around on the fix.

**Comment by redaxmedia** [comment]
I release 5.0.1 ... thanks again for letting me know. Please open another issue with a screenshot if possible. I guess cleaning the lines does not work...
