### ISSUE TITLE
Yarn lock not being respected

### ISSUE THREAD

**Issue by AshMcConnell** [redaxmedia/handpick#3]
Hi,

Is it possible to respect the versions in the yarn.lock file?  

Also is it possible to pass the --offline parameter?

Thanks!
Ash

**Comment by redaxmedia** [comment]
Sorry, but handpick is using an approach that manipulates the `package.json` and therefore I see no easy way to support lockfiles at this moment.

Let me give you a little insight what handpick does once you start it:

1. Creating a collection of targeted and filtered dependencies
1. Prefixing the original keys to `__dependencies` and `__devDependencies`
1. Creating the temporary key `dependencies` with collection from `1`
1. Running the package manager's install command
1. Reverting the `package.json` to the original

Therefore... running yarn without `--no-lockfile` won`t use the depedencies we want, right?

According to the request to pass arguments - this is a valid point. I would prefer to override the [option.json](https://github.com/redaxmedia/handpick/blob/master/option.json) by passing a config file like `.handpick` or just use it once it exists!?

**Comment by redaxmedia** [comment]
According to the request to pass arguments - this is a valid point. I would prefer to override the [option.json](https://github.com/redaxmedia/handpick/blob/master/option.json) by passing a config file like `.handpick` or just use it once it exists!?

```
handpick --config=.handpick
```

**Comment by AshMcConnell** [comment]
Oh that's great, I'll try it later today :)

**Comment by AshMcConnell** [comment]
Yep, that works great for me!  Thanks for your hard work.  I'm not sure we are going to use it in our gitlab CI workflow (we are having success with changing the GIT_CLEAN_FLAGS),  but I'm absolutely sure I'll use this in the future.  Thanks!

**Comment by redaxmedia** [comment]
Great, I just released 2.0.0 and close this issue now.

**Comment by redaxmedia** [comment]
@ AshMcConnell There is an experimental feature branch to work around yarn.lock https://github.com/redaxmedia/handpick/issues/8 ... let me know if this is a game changer for you.
