### ISSUE TITLE
I want to install `lintDependencies` with `dependencies` and `devDependencies`

### ISSUE THREAD

**Issue by Neos21** [redaxmedia/handpick#32]
I want to install `lintDependencies` with `dependencies` and `devDependencies`.
But, `--target` option works only `lintDependencies` or `dependencies & devDependencies`.
When I use `--target=lintDependencies` option, the npm packages installed are removed.

**Comment by henryruhs** [comment]
You have to pass the desired dependencies as a list.

```
--target=dependencies devDependencies lintDependencies
```
