### ISSUE TITLE
Idea: support multiple files

### ISSUE THREAD

**Issue by IanVS** [redaxmedia/handpick#5]
In a monorepo, it might be nice to be able to run one `handpick` command against multiple `package.json` files.  This might be done by allowing `file` to be an array.

Just an idea.  It's also possible to just run `handpick` multiple times, it's just a bit more cumbersome.

**Comment by redaxmedia** [comment]
Well, not sure if this is in the scope of this project.

A pretty good reason for something like that would be downloading conditional dependencies in different threads to parallelize whole the process.

I can give this a shot using different cache folders to prevent conflicts. Open for PRs aswell...

**Comment by redaxmedia** [comment]
I tried this but parallel download are not speeding things up, will close this for now.
