### ISSUE TITLE
Add `engines` to the project

### ISSUE THREAD

**Issue by IanVS** [redaxmedia/handpick#6]
It looks like this project is using `fs.promises`, which was added in Node 10.  Might be worth specifying that in the `engines` for the project.  I'm stuck on version 8, so I can't use this, unfortunately.  :(  It's good to get an explanation as to why, rather than hitting a runtime error when I try to use it.  `TypeError: Cannot read property 'readFile' of undefined`.

**Comment by redaxmedia** [comment]
I released `2.1.0-beta.1` to support NodeJS 8 and 9 aswell.

Testing this against CI only, so please report if this is working for you so I can release a stable version.

**Comment by redaxmedia** [comment]
Released `2.1.0` now...
